name: llava-pretrain
path: ${oc.env:VLM_DATA_ROOT}/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json
type: json
lazy_preprocess: True
is_multimodal: True
image_folder: ${oc.env:VLM_DATA_ROOT}/LLaVA-Pretrain/images
