name: llava-finetune
path: ${oc.env:VLM_DATA_ROOT}/LLaVA-Instruct-150K/llava_v1_5_mix665k.json
type: json
lazy_preprocess: True
is_multimodal: True
image_folder: ${oc.env:VLM_DATA_ROOT}/llava-images
image_aspect_ratio: pad
