deepspeed: /pasteur/u/yiming/small-vlm/src/vlm/config/deepspeed/zero3.json
version: v1
bf16: True
tf32: True
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
warmup_ratio: 0.03
lr_scheduler_type: cosine
gradient_checkpointing: True
dataloader_num_workers: 4
report_to: wandb
# resume_from_checkpoint: resume_model_path
from_pretrained: /pasteur/u/yiming/small-vlm/outputs/2025-07-02/17-18-17
group_by_modality_length: True
save_steps: 1000

defaults:
  - unfreeze: unfrozen
  - learning_rate: llava-next-finetune
  - weight_decay: default
