defaults:
  - model: default
  - training: default
  - dataset: default
  - override hydra/job_logging: logging/rich.yaml
  - override hydra/hydra_logging: logging/rich.yaml
  - _self_

hydra:
  job:
    chdir: true
  job_logging:
    root:
      level: DEBUG