defaults:
  - _self_

language_model:
  hf_name: lmsys/vicuna-7b-v1.5
  max_seq_length: 2048

visual_encoder:
  hf_name: /pasteur2/u/yuhuiz/yiming/clip_datacomp_s
  output_layer: -2
  use_cls_token: False

connector:
  name: mlp_2_gelu
  type: mlp

name: llama3.2-3b
