defaults:
  - _self_

language_model:
  hf_name: lmsys/vicuna-7b-v1.5
  max_seq_length: 2048

visual_encoder:
  hf_name: google/siglip-so400m-patch14-384
  output_layer: -1
  use_all_tokens: False
  use_cls_token: True

connector:
  name: mlp_2_gelu
  type: mlp

name: llava-7b-siglip
