defaults:
  - _self_

language_model:
  hf_name: Qwen/Qwen2.5-7B-Instruct
  max_seq_length: 4096

visual_encoder:
  hf_name: google/siglip2-so400m-patch14-384
  output_layer: -1
  use_cls_token: True

connector:
  name: mlp_2_gelu
  type: mlp

name: qwen2.5-7b
