defaults:
  - mode: train
  - model: small-vlm
  - trainer: pretrain
  - dataset: llava-pretrain
  - override hydra/job_logging: rich
  - _self_

hydra:
  job:
    chdir: true
  job_logging:
    root:
      level: DEBUG