defaults:
  - cfg
  - mode: train
  - model: small-vlm
  - trainer: pretrain
  - inference: default
  - dataset: llava-pretrain
  - override hydra/job_logging: rich
  - _self_

trainer:
  num_training_samples: 10000
  batch_size: 8
  accumulate_grad_batches: 1

hydra:
  job:
    chdir: true
  job_logging:
    root:
      level: INFO