defaults:
  - cfg
  - model: llava-7b-unified
  - trainer: finetune-unified
  - inference: default
  - dataset: unified-finetune
  - override hydra/job_logging: rich
  - _self_

hydra:
  job:
    chdir: true
  job_logging:
    root:
      level: INFO
  run:
    dir: outputs/${model.name}/${trainer.name}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${model.name}/${trainer.name}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
